export const CREATE_WORKOUT = "CREATE_WORKOUT";
export const DELETE_WORKOUT = "DELETE_WORKOUT";
export const EDIT_WORKOUT = "EDIT_WORKOUT";

export const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER";

export const TYPE_RUNNING = "TYPE_RUNNING";
export const TYPE_WALKING = "TYPE_WALKING";
export const TYPE_SKIING = "TYPE_SKIING";
export const TYPE_CYCLING = "TYPE_CYCLING";
